@base_url=http://localhost:8005

### page
GET {{base_url}}/m-biodata?page=1&size=2

### sort
GET {{base_url}}/m-biodata?sort=[{"id":"fullname", "desc":true}]

### filter
GET {{base_url}}/m-biodata?filter=[{"id":"fullname", "value":"3", "matchMode": "CONTAINS", "dataType": "TEXT", "mode": "AND"}]

### index
GET {{base_url}}/m-biodata/1

### new
POST {{base_url}}/m-biodata
Content-Type: application/json

{
    "id": 2,
    "fullname":"my-name 2",
    "mobilePhone":"084321829345",
    "isDelete":false
}

### update
PUT {{base_url}}/m-biodata
Content-Type: application/json

{
    "id": 1,
    "fullname":"my-name1",
    "mobilePhone":"084321829345",
    "isDelete":false
}

### delete
DELETE {{base_url}}/m-biodata/1